- src/check.rs
- src/deploy.rs
- src/export_abi.rs
- src/main.rs
- src/new.rs
- src/project.rs
- src/tx.rs
- src/wallet.rs
```
Deploy / activation command failed: address 0x8578bdcb58da7b623a634ecf25b059528fb8ceb0 has 0 balance onchain – please refer to our Quickstart guide on obtaining
testnet ETH for deploying on Stylus here https://docs.arbitrum.io/stylus/stylus-quickstart
```
> Address Cargo Stylus Feedback

- src/deploy.rs
A small modification to deploy command messages.
> fix deploy command messages

- src/deploy.rs
- src/main.rs
- src/tx.rs
Uses less confusing colors and prints addresses in checksum format across the project
> Color Improvements and Addr Checksum

- src/project.rs
Adds a user-facing hint to the `NoWasmFound` error. A major cause seems to be having a `lib.rs` instead of a `main.rs`
Made using web UI. Didn't run linter or anything, sorry 😅
> doc: hint in error message

- .github/pull_request_template.md
- Cargo.lock
- Cargo.toml
- src/check.rs
- src/constants.rs
- src/deploy.rs
- src/new.rs
- src/project.rs
- src/util.rs
This PR supports the switchover to cdylib-centric Stylus projects
Additionally, this PR introduces a new template repo for minimal programs
- https://github.com/OffchainLabs/stylus-hello-world-minimal
> Switch to cdylibs

- src/project.rs
When a user tries to compile a program that exceeds the max, we will try again with some optimization flags. If it fails again, we seem to print out a message that looks duplicate, but is actually a bit different. This PR simplifies the second message so that it is clearer to the reader
> Simpler Message On Retrying Compilation With Nightly

- src/check.rs
- src/deploy.rs
- src/main.rs
- src/project.rs
- src/tx.rs
> Minor Fixes for UX

- cgen/Cargo.toml
Adds missing info to publish cargo-stylus-cgen to crates
> Add description / keywords to cgen crate

- README.md
The wat example on the README.md was out of date.
> Updated wat example

- Cargo.lock
- replay/Cargo.toml
- replay/src/trace.rs
If a user attempts to use cargo stylus replay on a trace tx that is a program deployment or activation, they would receive weird errors. This instead adds a nicer UX in case this occurs
> Detect if User Is Tracing Activation / Deployment Txs in Tracing and Exit Early

- check/src/main.rs
This RPC changes the default RPC of cargo-stylus to Arbitrum Sepolia
> Change default RPC to Arbitrum Sepolia

- main/src/main.rs
- replay/src/main.rs
Please provide a summary of the changes and any backward incompatibilities.
* Fixes #22. 
* Added conditional imports for unix and windows.
* modified command execution & error handling for both platforms.
* Tested on Windows 11 & Ubuntu 
> Add Windows Support

- .github/workflows/check.yml
- check/src/cache.rs
- check/src/deploy.rs
- check/src/main.rs
Allows for configuring a max fee per gas in gwei when deploying or activating programs via the CLI
> Allow Configurable Max Fee Per Gas in Tx Sending

- Cargo.lock
- check/src/cache.rs
- check/src/constants.rs
- check/src/main.rs
Latest Stylus cache manager operates on addresses instead of code hashes. This updates cargo stylus to align with that behavior. We also make the cache manager address a configurable flag of the command
> Update Deps And Cargo Stylus Cache With Latest Contract ABI

- main/src/main.rs
Fixes #54. The changes ensure that running `cargo stylus—-version` outputs the expected version information instead of returning the help message.
Also, resolved a minor issue with the duplication of the command `check` alias `c`.
> Fix: Ensure --version flag works correctly for cargo stylus

- check/src/cache.rs
- check/src/constants.rs
- check/src/deploy.rs
- check/src/main.rs
This PR fetches the stylus arbwasm cache manager addr from the arbwasmcache precompile instead of it being a flag provided by the user. Additionally, it prints an informational message telling the user they can use the stylus cache after a deployment
> Obtain Cache Manager Addr from ArbWasmCache Precompile + Informational Message About Cache on Deploy

- README.md
- check/OPTIMIZING_BINARIES.md
- check/VALID_WASM.md
- check/src/activate.rs
- check/src/cache.rs
- check/src/check.rs
- check/src/constants.rs
- check/src/deploy.rs
- check/src/export_abi.rs
- check/src/main.rs
- check/src/project.rs
- check/src/verify.rs
- main/src/main.rs
- replay/src/hostio.rs
- replay/src/trace.rs
Replace instances of program with contract for consistency where needed.
Closes #68
> Standardize Terminology to Contract

- util/src/text.rs
This solves a common problem when there is an extra new-line in the private key file. For instance:
Error: stylus deploy failed
Caused by:
0: failed to load wallet
1: invalid private key
2: Odd number of digits
> Trim white spaces when reading private key

- README.md
- check/Dockerfile
- check/src/cache.rs
- check/src/check.rs
- check/src/constants.rs
- check/src/deploy.rs
- check/src/docker.rs
- check/src/main.rs
- check/src/new.rs
- check/src/project.rs
- check/src/verify.rs
- main/src/main.rs
- replay/src/main.rs
Closes #66 
Closes #65
Closes #64
Closes #62 
Closes #52
> Miscellaneous Issue Resolution

- check/src/project.rs
Strip unknown and custom data sections from user WASMs as they may contain sensitive data that is unnecessary for the functioning of the program. This is done before we add our own custom section that includes the project's metadata hash, however.
> Strip Potentially Sensitive Sections from User WASMs

- main/src/docker.rs
- main/src/main.rs
- main/src/project.rs
This PR enforces a Cargo.lock and a version existing in the Cargo.toml's [package] section of a user's project directory, to make reproducible verification safer.
Closes #88
> Enforced Cargo.lock and Version in Cargo.toml for User Projects

- README.md
As there is no Github action for Windows currently, the Windows badge appears as a broken image/link. Removing this badge for now.
> Remove Windows badge

- Cargo.lock
- Cargo.toml
- Dockerfile
- main/src/docker.rs
- main/src/main.rs
Allows a deployer and verifier doing reproducible actions in Docker to specify the cargo stylus version flag to be used in their Docker image. When Cargo stylus runs deployments or verification through Docker, it downloads an image called `cargo-stylus-base:$VERSION`. It currently defaults to the local binary's version for cargo stylus, but verifiers such as Etherscan benefit from being able to specify the user's cargo stylus version during verification
> Include Optional Cargo Stylus Version Flag for Verification

- Cargo.lock
- Cargo.toml
- main/src/main.rs
This PR removes `cargo-stylus-version` from the command that gets run in a Docker container as part of reproducible verification. Prior cargo stylus versions to 0.5.2 did not have this flag, so we do not include it when running in Docker. This allows a verifier running 0.5.3 to verify programs that were deployed with >= 0.5.0
> Hotfix for Reproducible Verification

- README.md
Small update to readme for existing users that may not have seen the PSA on cargo stylus versions and contract verification.
> Update README.md with note on Arbiscan contract verification

- main/src/constants.rs
- main/src/main.rs
This PR adds the arb1 RPC as the default endpoint for cargo stylus, and also ignores custom extensions `cargo-stylus-check, cargo-stylus-cgen, cargo-stylus-replay` as those are now part of the main `cargo-stylus` binary.
> Add Arb1 RPC as Default URL and Ignore Deprecated Cargo Stylus Extensions

- main/src/main.rs
- main/src/trace.rs
A new **simulate** API has been added to the trace, allowing users to trace their transactions without submitting them to the network. This feature enables tracing by providing transaction fields alone, streamlining the process. 
Closes: INT-249
> simulate api for debug trace call

- main/src/cache.rs
This PR fixes the issue reported in NIT-2802 where the `cargo-stylus cache bid` subcommand did not set the from address on its calls, causing the zero address to be used and calls to fail due to insufficient funds.
Reproduced the reported issue prior to the fix:
```
$ target/debug/cargo-stylus cargo-stylus cache bid '--endpoint=http://localhost:8547' --priv
ate-key=0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659 0x11b57fe348584f0
42e436c6bf7c3c3def171de49 2                                                                 
Checking if contract can be cached...                                                       
Error: stylus cache place bid failed                                                        
Caused by: …
```
> Set from address on placeBid call

- Cargo.toml
Let crates.io know where to find README.md so it gets rendered properly.  Will take effect when the next version is published.
> Add readme to Cargo.toml

- main/src/main.rs
If using MacOS, `cargo stylus replay` needs to use `rust_lldb` instead of `rust_gdb`
> Replay osx support

- main/src/main.rs
The function call was passing the wrong parameter, so the deprecated check always returned false.
> Fix deprecated extension check

- README.md
- main/src/check.rs
This PR removes a hardcoded version from the README.md and intercepts the common missing import error that is a result of not specifying an #[entrypoint] in contracts that users frequently run into.
> Remove Hardcoded Version in README and Add Nicer Error

- Cargo.lock
- Cargo.toml
- main/Cargo.toml
- main/src/deploy/deployer.rs
- main/src/deploy/factory.rs
- main/src/deploy/mod.rs
- main/src/export_abi.rs
- main/src/main.rs
This PR adds support to deploying a Stylus contract using the Stylus Factory. The factory will deploy the contract, activate it, and initialize it by calling the constructor.
First, we add a new function (`get_constructor_signature`) in the export-abi module to get the constructor signature from the export binary. This function will call the binary and pass the `constructor` subcommand to get the constructor definition. If the SDK doesn't support constructors, the function will return that no constructor is present to be backward compatible.
Then, the code that deploys the contract will call `get_constructor_signature` to decide whether it should use the factory. If no constructors are present, cargo-stylus will behave as it did previously. If the contract has a constructor, the function …
> Add support to Stylus Constructors

- main/src/deploy/mod.rs
The current url (https://docs.arbitrum.io/stylus/concepts/stylus-cache-manage) we show is 404 now, we need to update it
> update cache url

- main/src/export_abi.rs
- main/src/main.rs
Added rust_features argument for the export-abi command in order to allow to generate abi for functionality marked with feature flags in the Rust smart contract code. I faced the lack of such functionality while adding feature specific code and extending our CI. 
For now, without this changes the only possible solution would be `cargo run --quiet --features=export-abi,your-own-feature --target=your-target  -- abi`.
> Add rust_features argument for the export-abi command

- main/src/cache.rs
- main/src/deploy/deployer.rs
- main/src/deploy/mod.rs
- main/src/main.rs
Because in rust [ethers](https://docs.rs/ethers-core/2.0.14/src/ethers_core/utils/mod.rs.html#496), the `eip1559_default_estimator` will set a high base_fee_per_gas and priority_fee to `EIP1559_FEE_ESTIMATION_DEFAULT_PRIORITY_FEE` (3_000_000_000) if network fee lower than this default value (`EIP1559_FEE_ESTIMATION_PRIORITY_FEE_TRIGGER `, 100_000_000_000), however, on arbitrum, the network fee is significant lower than this. And if the cli tool use this default fee to send tx which will cause the tx body's gas fee set super higher than what it actually needs and might lead to tx failed if users don't have that much balance in wallet.
Also, for `--max-fee-per-gas-gwei` config, it uses u128, however, user might input like `0.02` value, so we need to reset it to string and use a method to …
> Fix gas estimate and command issues

- main/src/deploy/mod.rs
Currently this tool will try to treat current projec as an rust sdk project (it will try to get `Cargo.toml` file and the file with export-abi) even when user set `--wasm-file=xx.wasm`, however, user in this case usually just want to provide one single xx.wasm file here to deploy and if users write the stylus program with other language will either not provide those files, so we should skip `export_abi::get_constructor_signature()` in this case.
> skip get_constructor_signature when set wasm-file

- main/src/export_abi.rs
- main/src/main.rs
This PR adds a simple command to print the contract constructor signature. If the contract doesn't have a constructor, it doesn't print anything.
Close https://linear.app/offchain-labs/issue/STY-231
> Add command to print constructor

- main/src/deploy/mod.rs
If cargo-stylus doesn't detect a constructor in the contract, check whether the arguments are passed by the user. If they are set, emit an error to avoid misleading the user.
Close STY-245
> Check whether constructor args are wrongly set

- main/src/check.rs
- main/src/get_initcode.rs
- main/src/main.rs
- main/src/project.rs
Added a command to print initcode. 
As part of this change, also extracted logic from `build_wasm` function into a common util.
e.g.
```
cargo stylus get-initcode --output initcode.txt
```
> Command to get initcode

- main/src/deploy/mod.rs
- main/src/main.rs
Add a feature flag that receives an optional constructor signature. Cargo-stylus uses this signature to parse the constructor arguments when the user passes the wasm-file flag. When using a wasm-file, cargo-stylus doesn't introspect the package so it can't detect whether the contract has a constructor.
Close [STY-253](https://linear.app/offchain-labs/issue/STY-253)
> Add flag to deploy wasm-files with constructors

- Cargo.lock
- Cargo.toml
- main/Cargo.toml
- main/src/activate.rs
- main/src/cache.rs
- main/src/check.rs
- main/src/constants.rs
- main/src/deploy/deployer.rs
- main/src/deploy/mod.rs
- main/src/export_abi.rs
- main/src/gen.rs
- main/src/main.rs
- main/src/project.rs
- main/src/trace.rs
- main/src/util/sys.rs
- main/src/verify.rs
- main/src/wallet.rs
This PR eliminates Ethers-rs as a dependency and migrates entirely to [alloy](https://alloy.rs/getting-started/installation.html) as our primary EVM-chain SDK.
In this migration, we reorganized certain functions, certain type parameters changed, and other ways of doing important tasks in cargo stylus now look different. This PR requires thorough testing of each cargo stylus feature to ensure they still work as expected.
> Consolidate Alloy Dependency and Remove Ethers.rs

- main/src/deploy/deployer.rs
- main/src/deploy/mod.rs
- main/src/main.rs
We deployed this contract using Create2, so it has the same address across all networks.
Close STY-252
> Set default address for Stylus Deployer

- main/src/deploy/deployer.rs
- main/src/deploy/mod.rs
- main/src/export_abi.rs
- main/src/verify.rs
* [Verify contract deployed with StylusDeployer](https://github.com/OffchainLabs/cargo-stylus/commit/fa303da403411de6dd198cdc540cba36bf8c69a3) 
When a contract has a constructor, its deployment transaction is a call
to StylusDeployer instead of a CREATE call. So, to verify the
deployment, the code decodes the transaction input before comparing it
with the project bytecode. The verification also prints the deployment
parameters sent to StylusDeployer.
Close [STY-257](https://linear.app/offchain-labs/issue/STY-257)
Other minor fixes included in this PR:
* [Add print to when checking for constructor](https://github.com/OffchainLabs/cargo-stylus/commit/fc8f2e00cfc6427f46a3737fac8af0fe699916e8) 
* [Remove redundant compilation step in …
> Verify contract deployed with StylusDeployer

- main/src/main.rs
The main binary failed to get the input data from the transaction. Solve the issue by calling the correct method.
Close STY-267
> Fix cargo stylus replay
